In [1]:
import xgboost
import pandas as pd
# First XGBoost model for Pima Indians dataset
from numpy import loadtxt
from xgboost import XGBClassifier 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_boston

In [2]:
adult_data = pd.read_csv('../data/DecisionTree.csv')
feature_columns = ['workclass', 'education', 'marital-status', 'occupation', 'relationship', 'race', 'gender', 'native-country']
label_column = ['income']
adult_data.head()

workclass   education       marital-status          occupation  \
0          State-gov   Bachelors        Never-married        Adm-clerical   
1   Self-emp-not-inc   Bachelors   Married-civ-spouse     Exec-managerial   
2            Private     HS-grad             Divorced   Handlers-cleaners   
3            Private        11th   Married-civ-spouse   Handlers-cleaners   
4            Private   Bachelors   Married-civ-spouse      Prof-specialty   

     relationship    race   gender  native-country  income  
0   Not-in-family   White     Male   United-States   <=50K  
1         Husband   White     Male   United-States   <=50K  
2   Not-in-family   White     Male   United-States   <=50K  
3         Husband   Black     Male   United-States   <=50K  
4            Wife   Black   Female            Cuba   <=50K

In [3]:
#区分特征和目标列
from sklearn.preprocessing import LabelEncoder

X = adult_data.values[:,1:8]
Y = adult_data.values[:,8]

#Xbgoost只支持数值型
#https://flashgene.com/archives/30104.html
label_encoder = LabelEncoder()
label_encoder = label_encoder.fit(Y)
label_encoded_y = label_encoder.transform(Y)
print(label_encoded_y)

label_encoded_x = pd.DataFrame(X.copy())
for col in pd.DataFrame(X):
    label_encoded_x[col] = LabelEncoder().fit_transform(label_encoded_x[col])
print(label_encoded_x)

[0 0 0 ... 0 0 1]
        0  1   2  3  4  5   6
0       9  4   1  1  4  1  39
1       9  2   4  0  4  1  39
2      11  0   6  1  4  1  39
3       1  2   6  0  2  1  39
4       9  2  10  5  2  0   5
...    .. ..  .. .. .. ..  ..
32556   7  2  13  5  4  0  39
32557  11  2   7  0  4  1  39
32558  11  6   1  4  4  0  39
32559  11  4   1  3  4  1  39
32560  11  2   4  5  4  0  39

[32561 rows x 7 columns]


In [4]:
label_encoded_y

array([0, 0, 0, ..., 0, 0, 1])

In [5]:
label_encoded_x

0  1   2  3  4  5   6
0       9  4   1  1  4  1  39
1       9  2   4  0  4  1  39
2      11  0   6  1  4  1  39
3       1  2   6  0  2  1  39
4       9  2  10  5  2  0   5
...    .. ..  .. .. .. ..  ..
32556   7  2  13  5  4  0  39
32557  11  2   7  0  4  1  39
32558  11  6   1  4  4  0  39
32559  11  4   1  3  4  1  39
32560  11  2   4  5  4  0  39

[32561 rows x 7 columns]

In [6]:
# split data into train and test sets
seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(label_encoded_x, Y, test_size=test_size, random_state=seed)
# fit model no training data
model = XGBClassifier()
model.fit(X_train, y_train)
# make predictions for test data
from sklearn.metrics import recall_score

y_pred = model.predict(X_test)
print(model.score(X_test, y_test))
print(recall_score(y_test,model.predict(X_test),average='macro'))

[19:23:19] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


/usr/local/lib/python3.7/site-packages/xgboost/sklearn.py:888: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)


0.8254234133631119
0.7312406951462349


In [7]:
#对比下逻辑回归的数据集

pd.set_option('display.max_columns', 500)
import zipfile
with zipfile.ZipFile('../data/KaggleCredit2.csv.zip', 'r') as z:   ##读取zip里的文件
    f = z.open('KaggleCredit2.csv')
    data = pd.read_csv(f, index_col=0)
data.head()

SeriousDlqin2yrs  RevolvingUtilizationOfUnsecuredLines   age  \
0                 1                              0.766127  45.0   
1                 0                              0.957151  40.0   
2                 0                              0.658180  38.0   
3                 0                              0.233810  30.0   
4                 0                              0.907239  49.0   

   NumberOfTime30-59DaysPastDueNotWorse  DebtRatio  MonthlyIncome  \
0                                   2.0   0.802982         9120.0   
1                                   0.0   0.121876         2600.0   
2                                   1.0   0.085113         3042.0   
3                                   0.0   0.036050         3300.0   
4                                   1.0   0.024926        63588.0   

   NumberOfOpenCreditLinesAndLoans  NumberOfTimes90DaysLate  \
0                             13.0                      0.0   
1                              4.0                      0.0   
2                              2.0                      1.0   
3                              5.0                      0.0   
4                              7.0                      0.0   

   NumberRealEstateLoansOrLines  NumberOfTime60-89DaysPastDueNotWorse  \
0                           6.0                                   0.0   
1                           0.0                                   0.0   
2                           0.0                                   0.0   
3                           0.0                                   0.0   
4                           1.0                                   0.0   

   NumberOfDependents  
0                 2.0  
1                 1.0  
2                 0.0  
3                 0.0  
4                 0.0

In [8]:
#去掉为空的数据,inplace=True:直接在原对象上修改
data.dropna(inplace=True)
y = data['SeriousDlqin2yrs']
x = data.drop('SeriousDlqin2yrs', axis=1)
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=test_size, random_state=seed)
print(x_test.shape)
print(x_train.shape)
print(y_test.shape)
print(y_train.shape)

(35854, 10)
(72794, 10)
(35854,)
(72794,)


In [13]:
model_2 = XGBClassifier(use_label_encoder=False)
model_2.fit(x_train, y_train)
y_test_pred = model_2.predict(x_test)
print(model_2.score(x_test, y_test))
print(recall_score(y_test, y_test_pred,average='macro'))

[19:28:42] WARNING: /Users/travis/build/dmlc/xgboost/src/learner.cc:1061: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
0.936631896022759
0.5929253205408304


In [12]:
# 计算混淆矩阵，并显示
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_test_pred)
cm

array([[33113,   353],
       [ 1919,   469]])